# TODO: tää on paskaa. ei oo tehty testispeksiä varten.

version: "3"

services:
  kanban_frontend_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      target: setup
    environment:
      - BASE_URL=${BASE_URL}${BACKEND_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - node_modules:/frontend/node_modules
      - ./frontend:/frontend
    ports:
      - "9000:9000"

  kanban_backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    ports:
      - "5000:5000"

  kanban_database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./developmentdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  kanban_cypress:
    build:
      context: ./e2e
      dockerfile: Dockerfile.cypress
    environment:
      - BASE_URL=http://kanban_frontend_dev:9000/demo
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
    depends_on:
      - kanban_frontend_dev
      - kanban_backend_dev
      - kanban_database
    volumes:
      - ./init.sql:/init.sql

volumes:
  node_modules:
