version: "3"

services:
  kanban_frontend_dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      target: setup
    environment:
      - BASE_URL=${BASE_URL}
      - FRONTEND_PORT=${FRONTEND_PORT}
    volumes:
      - node_modules:/frontend/node_modules
      - ./frontend:/frontend
    ports:
      - "9000:9000"

  kanban_backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    ports:
      - "5000:5000"

  kanban_database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./developmentdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  node_modules:
