FROM python:3.8-slim

WORKDIR /backend

COPY ./requirements.txt /backend/
RUN apt-get update && apt-get install -y postgresql-client
RUN pip install -r requirements.txt

COPY . /backend

EXPOSE 5000

CMD ["python", "app.py"]
