name: CI

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:9000
      DB_NAME: temp_database
      DB_USER: temp_username
      DB_PASSWORD: temp_password
      DB_HOST: kanban_database
      POSTGRES_USER: temp_username
      POSTGRES_PASSWORD: temp_password
      POSTGRES_DB: temp_database

    steps:
      - uses: actions/checkout@v2

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.prod.yml up -d

      - name: Install Cypress Dependencies
        working-directory: ./e2e
        run: npm install

      - name: Wait for Frontend to be ready
        run: |
          echo "Waiting for frontend service to be ready..."
          while ! nc -z localhost 9000; do   
            sleep 1 # odottaa yhden sekunnin ja yrittää uudestaan
          done
          echo "Frontend service is up and running!"

      - name: Install Cypress Binary
        working-directory: ./e2e
        run: npx cypress install

      - name: Verify Cypress Binary
        working-directory: ./e2e
        run: npx cypress verify

      - name: Run Cypress Tests
        working-directory: ./e2e
        run: npx cypress run

      - name: Shutdown
        run: docker-compose -f docker-compose.prod.yml down
