name: CI

on: [pull_request, commit]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:9000
      DB_NAME: temp_database
      DB_USER: temp_username
      DB_PASSWORD: temp_password
      DB_HOST: kanban_database
      POSTGRES_USER: temp_username
      POSTGRES_PASSWORD: temp_password
      POSTGRES_DB: temp_database

    steps:
      - uses: actions/checkout@v2

      # Cache Cypress binary
      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.prod.yml up -d

      # Install Cypress Dependencies
      - name: Install Cypress Dependencies
        working-directory: ./e2e
        run: npm install

      # Wait for Frontend to be ready
      - name: Wait for Frontend to be ready
        run: |
          echo "Waiting 60 seconds for frontend service to be ready..."
          sleep 60
          echo "Continuing to the next step..."

      # Install Cypress Binary
      - name: Install Cypress Binary
        working-directory: ./e2e
        run: npx cypress install

      # Verify Cypress Binary
      - name: Verify Cypress Binary
        working-directory: ./e2e
        run: npx cypress verify

      # Print Backend logs
      - name: Print Backend logs
        run: |
          echo "Printing backend logs..."
          docker-compose -f docker-compose.prod.yml logs kanban_backend_prod

      # Print Database logs
      - name: Print Database logs
        run: |
          echo "Printing database logs..."
          docker-compose -f docker-compose.prod.yml logs kanban_database

      # Run Cypress Tests
      - name: Run Cypress Tests
        working-directory: ./e2e
        run: npx cypress run

      # Shutdown
      - name: Shutdown
        run: docker-compose -f docker-compose.prod.yml down
